language: ruby

services:
  - postgresql

rvm:
  - 2.0.0

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.3.4
  - REDMINE_VER=2.4.7
  - REDMINE_VER=2.5.3
  - REDMINE_VER=2.6.5
  - REDMINE_VER=3.0.3

before_install:
  - export PLUGIN_NAME=redmine_simple
  - export DB=postgresql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH
  - git clone --depth=1 https://github.com/Undev/redmine__select2.git $REDMINE_PATH/plugins/redmine__select2

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
